services:
  twitter-db:
    container_name: twitter-db
    image: postgres:14
    restart: always
    networks:
      twitter-net:
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "127.0.0.1:5434:5432"

  twitter:
    container_name: twitter
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    networks:
      twitter-net:
    environment:
      - JDBC_URL=jdbc:postgresql://twitter-db:5432/${POSTGRES_DB}
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_BOT_USERNAME
      - TELEGRAM_OWNER_ID
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - YT_DLP_PATH=/usr/local/bin/yt-dlp
      - TIKTOK_SERVICE_URL=http://tiktok:3000
    depends_on:
      - twitter-db


  tiktok:
    build:
      dockerfile: Dockerfile-tiktok
      context: tikitoki
    container_name: tiktok_container
    restart: always
    networks:
      twitter-net:
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production

volumes:
  postgres-data:

networks:
  twitter-net: