[start-command-text]
en="Hello! I am a bot that can help with Twitter/TikTok. To get started, please send me a link you want to see."
ru="Привет! Я бот, который может помочь с Twitter/TikTok. Чтобы начать, пожалуйста, отправьте мне ссылку, который вы хотите увидеть."
ua="Привіт! Я бот, який може допомогти з Twitter/TikTok. Щоб почати, будь ласка, надішліть мені посилання, який ви хочете побачити."

[language-command-text]
en="Choose language for translation"
ru="Выберите язык для перевода"
ua="Оберіть мову для перекладу"

[language-command-button]
en="English"
ru="Русский"
ua="Українська"

[language-changed-text]
en="{} chose the chat language: English"
ru="{} выбрал выбрали язык чата: Русский"
ua="{} обрав мову чату: Українська"

[tweet-fixupx]
en="Something wrong, but uou can see tweet in Instant View: {}"
ru="Что-то пошло не так, но вы можете посмотреть твит в Instant View: {}"
ua="Щось пішло не так, але ви можете подивитися твіт в Instant View: {}"

[tweet-header]
en="<a href=\"{}\">Tweet</a> from {} by {}"
ru="<a href=\"{}\">Твит</a> от {} by {}"
ua="<a href=\"{}\">Твіт</a> від {} by {}"

[language-callback-expired]
en="Sorry, but the time for choosing the language has expired. Please, try again."
ru="Извините, но время для выбора языка истекло. Пожалуйста, попробуйте еще раз."
ua="Вибачте, але час для вибору мови вичерпано. Будь ласка, спробуйте ще раз."


[translate_video_command_no_reply]
en="For translation, please reply to the message with the video"
ru="Для перевода, пожалуйста, ответьте на cообщение с видео"
ua="Для перекладу, будь ласка, відповідайте на повідомлення з відео"

[translate_video_command_no_urls]
en="Sorry, but I can't find any URLs in your message. Please, try again."
ru="Извините, но я не могу найти никаких URL в вашем сообщении. Пожалуйста, попробуйте еще раз."
ua="Вибачте, але я не можу знайти жодних URL в вашому повідомленні. Будь ласка, спробуйте ще раз."

[translate_video_command_video_too_big]
en="Sorry, but the video is too big."
ru="Извините, но видео слишком большое."
ua="Вибачте, але відео занадто велике."

[telegram-desc]
en="Telegram bot for translating tweets"
ru="Телеграм бот для перевода твитов"
ua="Телеграм бот для перекладу твітів"

[telegram-short-desc]
en="Telegram bot for translating tweets"
ru="Телеграм бот для перевода твитов"
ua="Телеграм бот для перекладу твітів"

[telegram-name]
en="Twitter Translate Bot"
ru="Переводчик твитов"
ua="Перекладач твітів"

[tweet-private]
en="Sorry, but the tweet is private."
ru="Извините, но твит закрытый."
ua="Вибачте, але твіт приватний."

[tweet-not-found]
en="Sorry, but the tweet was not found or account is private."
ru="Извините, но твит не найден или аккаунт приватный."
ua="Вибачте, але твіт не знайдено або аккаунт приватний."

[tweet-api-fail]
en="Sorry, but an error occurred while processing the tweet."
ru="Извините, но произошла ошибка при обработке твита."
ua="Вибачте, але сталася помилка під час обробки твіту."

[tweet-idk]
en="Sorry, but I don't know how to process this tweet."
ru="Извините, но я не знаю, как обработать этот твит."
ua="Вибачте, але я не знаю, як обробити цей твіт."

[tweet-telegram-validate-error]
en="Sorry, but the tweet is not valid for send."
ru="Извините, но твит не действителен для отправки."
ua="Вибачте, але твіт не є дійсним для відправки."

[tweet-telegram-error]
en="Sorry, but an error occurred while sending the tweet."
ru="Извините, но произошла ошибка при отправке твита."
ua="Вибачте, але сталася помилка під час відправлення твіту."

[tweet-unknown-error]
en="Sorry, but an unknown error occurred."
ru="Извините, но произошла неизвестная ошибка."
ua="Вибачте, але сталася невідома помилка."

[tweet-long-error]
en="Sorry, but the tweet is too long."
ru="Извините, но твит слишком длинный."
ua="Вибачте, але твіт занадто довгий."

[yt-dlp-cookies-expired]
en="Please ping author for update cookies"
ru="Пожалуйста, пинганите автора для обновления куков"
ua="Будь ласка, пінгуйте автора для оновлення куків"

[yt-dlp-rate-limit]
en="Rate limit exceeded. Please try again later."
ru="Превышен лимит запросов. Пожалуйста, попробуйте позже."
ua="Перевищено ліміт запитів. Будь ласка, спробуйте пізніше."
